version: "3.9"
services:
  ##Database config
  mysql:
    container_name: kvstore_db
    image: mysql:8.0.31
    ports:
      - "6601:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    volumes:
      - .data/db:/var/lib/mysql
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
