version: "3.9"
services:
  kvstore:
    container_name: kvstore-service
    image: kvstore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    restart: unless-stopped
  kvstore2:
    container_name: kvstore-service-2
    image: kvstore
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8002:8001"
    depends_on:
      - db
    restart: unless-stopped
  ##Database config
  db:
    image: mysql:8.0.31
    ports:
      - "6601:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3.7-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
volumes:
  db_data:
    driver: local
