apiVersion: v1
kind: Service
metadata:
  name: kvstore-db
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: kvstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-db
  labels:
    app: kvstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvstore
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
        - name: kvstore-db
          image: kvstore-mysql
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
