apiVersion: v1
kind: Service
metadata:
  name: kvstore-service
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: kvstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore-service
  labels:
    app: kvstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kvstore
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
        - name: kvstore
          image: kvstore-k8s:a1bd5905f02606a760ec6af57be6ef97ba69ade1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
